fete_en_fr = {
    "Erev Pesach": "Veille de Pessa'h",
    "Pesach I": "1er jour de Pessa'h",
    "Pesach II": "2e jour de Pessa'h",
    "Pesach III (CH’’M)": "Hol Hamoed Pessa'h",
    "Pesach IV (CH’’M)": "Hol Hamoed Pessa'h",
    "Pesach V (CH’’M)": "Hol Hamoed Pessa'h",
    "Pesach VI (CH’’M)": "Hol Hamoed Pessa'h",
    "Pesach VII": "7e jour de Pessa'h",
    "Pesach VIII": "8e jour de Pessa'h",
    "Erev Shavuot": "Veille de Chavouot",
    "Shavuot I": "1er jour de Chavouot",
    "Shavuot II": "2e jour de Chavouot",
    "Erev Rosh Hashana": "Veille de Roch Hachana",
    "Rosh Hashana I": "1er jour de Roch Hachana",
    "Rosh Hashana II": "2e jour de Roch Hachana",
    "Erev Yom Kippur": "Veille de Yom Kippour",
    "Yom Kippur": "Yom Kippour",
    "Erev Sukkot": "Veille de Souccot",
    "Sukkot I": "1er jour de Souccot",
    "Sukkot II": "2e jour de Souccot",
    "Sukkot III (CH’’M)": "Hol Hamoed Souccot",
    "Sukkot IV (CH’’M)": "Hol Hamoed Souccot",
    "Sukkot V (CH’’M)": "Hol Hamoed Souccot",
    "Sukkot VI (CH’’M)": "Hol Hamoed Souccot",
    "Sukkot VII (Hoshana Raba)": "Hoshana Raba",
    "Shemini Atzeret": "Chemini Atseret",
    "Simchat Torah": "Sim'hat Torah",
    "Chanukah: 1 Candle": "Hanoucca - 1ère bougie",
    "Chanukah: 2 Candles": "Hanoucca - 2e bougie",
    "Chanukah: 3 Candles": "Hanoucca - 3e bougie",
    "Chanukah: 4 Candles": "Hanoucca - 4e bougie",
    "Chanukah: 5 Candles": "Hanoucca - 5e bougie",
    "Chanukah: 6 Candles": "Hanoucca - 6e bougie",
    "Chanukah: 7 Candles": "Hanoucca - 7e bougie",
    "Chanukah: 8 Candles": "Hanoucca - 8e bougie",
    "Erev Purim": "Veille de Pourim",
    "Purim": "Pourim",
    "Ta’anit Esther": "Jeûne d'Esther",
    "Ta’anit Bechorot": "Jeûne des premiers-nés",
    "Tu BiShvat": "Tou Bichvat",
    "Lag BaOmer": "Lag BaOmer",
    "Tisha B'Av": "Ticha Béav",
    "Tzom Tammuz": "Jeûne du 17 Tamouz",
    "Tzom Gedaliah": "Jeûne de Guédalia",
    "Asara B’Tevet": "Jeûne du 10 Tevet",
    "Yom HaAtzma’ut": "Yom Haatsmaout",
    "Rosh Chodesh Cheshvan": "Roch Hodech Hechvan",
    "Rosh Chodesh Kislev": "Roch Hodech Kislev",
    "Rosh Chodesh Tevet": "Roch Hodech Tevet",
    "Rosh Chodesh Sh’vat": "Roch Hodech Chvat",
    "Rosh Chodesh Adar I": "Roch Hodech Adar I",
    "Rosh Chodesh Adar II": "Roch Hodech Adar II",
    "Rosh Chodesh Adar": "Roch Hodech Adar",
    "Rosh Chodesh Nisan": "Roch Hodech Nissan",
    "Rosh Chodesh Iyyar": "Roch Hodech Iyar",
    "Rosh Chodesh Sivan": "Roch Hodech Sivan",
    "Rosh Chodesh Tamuz": "Roch Hodech Tamouz",
    "Rosh Chodesh Av": "Roch Hodech Av",
    "Rosh Chodesh Elul": "Roch Hodech Eloul"
}
