parasha_corrigee = {
    "Ki Teitzei": "Ki-Tetsé",
    "Ki Tavo": "Ki-Tavo",
    "Nitzavim": "Nitsavim",
    "Vayeilech": "Vayélèkh",
    "Ha’azinu": "Haazinou",
    "Bereshit": "Berechit",
    "Noach": "Noa'h",
    "Lech-Lecha": "Lekh Lékha",
    "Vayera": "Vayéra",
    "Chayei Sara": "Hayé Sarah",
    "Toldot": "Toledot",
    "Vayetzei": "Vayétsé",
    "Vayishlach": "Vayichla'h",
    "Vayeshev": "Vayéchev",
    "Miketz": "Mikets",
    "Vayigash": "Vayigach",
    "Vayechi": "Vaye'hi",
    "Shemot": "Chemot",
    "Vaera": "Vaéra",
    "Bo": "Bo",
    "Beshalach": "Bechala'h",
    "Yitro": "Yitro",
    "Mishpatim": "Michpatim",
    "Terumah": "Terouma",
    "Tetzaveh": "Tetsavé",
    "Ki Tisa": "Ki-Tissa",
    "Vayakhel-Pekudei": "Vayakhel - Pékoudé",
    "Vayikra": "Vayikra",
    "Tzav": "Tsav",
    "Shmini": "Chémini",
    "Tazria-Metzora": "Tazria - Metsora",
    "Achrei Mot-Kedoshim": "A'haré Mot - Kedochim",
    "Emor": "Emor",
    "Behar-Bechukotai": "Béhar - Bé'houkotaï",
    "Bamidbar": "Bamidbar",
    "Nasso": "Nasso",
    "Beha’alotcha": "Béhaalotékha",
    "Sh’lach": "Chéla'h Lekha",
    "Korach": "Kora'h",
    "Chukat-Balak": "Houkat - Balak",
    "Pinchas": "Pin'has"
}
